FROM docker.io/library/node:latest AS build
# Build-time args (populated by GitHub Actions)
ARG COUNTER_API_TOKEN
ARG COUNTER_WORKSPACE
ARG COUNTER_COUNTER_SLUG
ARG COUNTER_FULL_PATH
ARG APP_VERSION
WORKDIR /app
COPY . .
# Ensure envs are available during build for quasar build-time injection
ENV COUNTER_API_TOKEN=${COUNTER_API_TOKEN}
ENV COUNTER_WORKSPACE=${COUNTER_WORKSPACE}
ENV COUNTER_COUNTER_SLUG=${COUNTER_COUNTER_SLUG}
ENV COUNTER_FULL_PATH=${COUNTER_FULL_PATH}
ENV APP_VERSION=${APP_VERSION}
RUN npm install && npm run build

FROM docker.io/library/nginx:alpine
# Propagate envs to runtime container (for future diagnostics or dynamic usage)
ARG COUNTER_API_TOKEN
ARG COUNTER_WORKSPACE
ARG COUNTER_COUNTER_SLUG
ARG COUNTER_FULL_PATH
ARG APP_VERSION
ENV COUNTER_API_TOKEN=${COUNTER_API_TOKEN}
ENV COUNTER_WORKSPACE=${COUNTER_WORKSPACE}
ENV COUNTER_COUNTER_SLUG=${COUNTER_COUNTER_SLUG}
ENV COUNTER_FULL_PATH=${COUNTER_FULL_PATH}
ENV APP_VERSION=${APP_VERSION}
COPY --from=build /app/dist/spa /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8888

