FROM node:latest AS build
# Build-time args (populated by GitHub Actions)
ARG COUNTER_API_TOKEN
ARG COUNTER_WORKSPACE
ARG COUNTER_COUNTER_SLUG
ARG COUNTER_FULL_PATH
WORKDIR /app
COPY . .
# Ensure envs are available during build for quasar build-time injection
ENV COUNTER_API_TOKEN=${COUNTER_API_TOKEN}
ENV COUNTER_WORKSPACE=${COUNTER_WORKSPACE}
ENV COUNTER_COUNTER_SLUG=${COUNTER_COUNTER_SLUG}
ENV COUNTER_FULL_PATH=${COUNTER_FULL_PATH}
RUN npm install && npm install counterapi && npm run build

FROM nginx:alpine
# Propagate envs to runtime container (for future diagnostics or dynamic usage)
ARG COUNTER_API_TOKEN
ARG COUNTER_WORKSPACE
ARG COUNTER_COUNTER_SLUG
ARG COUNTER_FULL_PATH
ENV COUNTER_API_TOKEN=${COUNTER_API_TOKEN}
ENV COUNTER_WORKSPACE=${COUNTER_WORKSPACE}
ENV COUNTER_COUNTER_SLUG=${COUNTER_COUNTER_SLUG}
ENV COUNTER_FULL_PATH=${COUNTER_FULL_PATH}
COPY --from=build /app/dist/spa /usr/share/nginx/html
EXPOSE 80

